language: elixir
elixir:
  - 1.0.5

addons:
  postgresql: "9.4"
services:
  - postgresql

before_script:
  - ./scripts/setup.sh

after_script:
  - mix deps.get --only docs
  - MIX_ENV=docs mix inch.report
